#!/usr/bin/env bash

# Resolve the absolute path to the directory where this script is located, allowing helper scripts and resources to be referenced reliably regardless of the current working directory or how the script was invoked
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# -------------------------------
# Initialize variables
# -------------------------------

# Empty variables to store user-provided paths
FASTQS=""
READ_LENGTH=150
REF_TRANSCRIPTOME=""
OUTPUT_DIR=""
TEMP_DIR=""


# -------------------------------
# Define a help/usage function
# -------------------------------

# Explain each expected command-line option
usage() {
  echo "Usage: $0 -f <FASTQ_DIR> -l <READ_LENGTH> -r <REF_TRANSCRIPTOME_DIR> -o <OUTPUT_DIR> -t <TEMP_DIR>"
  echo
  echo "  -f FASTQ_DIR              Directory containing sequencing FASTQ files"
  echo "  -l READ_LENGTH            Read length (default: 150)"
  echo "  -r REF_TRANSCRIPTOME_DIR  Path to CellRanger-compatible reference transcriptome"
  echo "  -o OUTPUT_DIR             Output directory"
  echo "  -t TEMP_DIR               Temporary directory"
  echo
  exit 1
}


# -------------------------------
# Parse command-line options using getopts
# -------------------------------

# Parse command-line options
while getopts ":f:r:o:t:h" opt; do
  case $opt in
    f) FASTQS="$OPTARG" ;;
    l) READ_LENGTH="$OPTARG" ;;
    r) REF_TRANSCRIPTOME="$OPTARG" ;;
    o) OUTPUT_DIR="$OPTARG" ;;
    t) TEMP_DIR="$OPTARG" ;;
    h) usage ;;
    \?) echo "Invalid option -$OPTARG"; usage ;;
    :) echo "Option -$OPTARG requires an argument"; usage ;;
  esac
done

# Remove trailing slash (if present)
FASTQS="${FASTQS%/}"
REF_TRANSCRIPTOME="${REF_TRANSCRIPTOME%/}"
OUTPUT_DIR="${OUTPUT_DIR%/}"
TEMP_DIR="${TEMP_DIR%/}"

#
OUTPUT_DIR="$OUTPUT_DIR/$(basename "$FASTQS")_scHLAseq"


# -------------------------------
# Run cellranger count
# ------------------------------- 

# Create output directory for cellranger count
mkdir -p ""$OUTPUT_DIR"/cellranger_count/"

# Run the Cell Ranger count pipeline and write BAM files and all output results to 'cellranger_count' directory in output folder
cellranger count --id cellranger_count \
  --fastqs "$FASTQS" \
  --transcriptome "$REF_TRANSCRIPTOME" \
  --create-bam true \
  --output-dir ""$OUTPUT_DIR"/cellranger_count" \
  --localcores "$(nproc)" \
  --localmem "$(awk '/MemAvailable/ {printf "%.0f\n", $2/1024/1024}' /proc/meminfo)"


# -------------------------------
# Run arcasHLA
# ------------------------------- 

# Create output directory for arcasHLA genotype
mkdir -p $OUTPUT_DIR/arcashla_genotype/

# Extract HLA-related and unmapped reads from the Cell Ranger BAM file
arcasHLA extract $OUTPUT_DIR/cellranger_count/outs/possorted_genome_bam.bam \
  --unmapped \
  --single \
  --outdir $OUTPUT_DIR/arcashla_genotype/ \
  --temp $TEMP_DIR \
  --threads $(nproc)

# Perform HLA genotyping using the extracted reads
arcasHLA genotype $OUTPUT_DIR/arcashla_genotype/possorted_genome_bam.extracted.fq.gz \
  --single \
  --avg $READ_LENGTH \
  --outdir $OUTPUT_DIR/arcashla_genotype/ \
  --temp $TEMP_DIR \
  --threads $(nproc)

# Rename extracted_reads output files to remove the common prefix
for file in $OUTPUT_DIR/arcashla_genotype/possorted_genome_bam.*; do
  base=$(basename $file)
  newname=${base#possorted_genome_bam.}
  mv $file $OUTPUT_DIR/arcashla_genotype/$newname
done

# Retrieve IPD-IMGT/HLA allele sequences for arcasHLA-identified class II alleles
$SCRIPT_DIR/scripts/fetch.HLA.allele.seqs.R \
  -g $OUTPUT_DIR/arcashla_genotype/genotype.json \
  -o $OUTPUT_DIR/arcashla_genotype/ \
  --class-II-only


# -------------------------------
# Re-align reads from chromosome 6 and unmapped reads to allelic-specific HLA reference sequences 
# ------------------------------- 

# Create output directory for allelic expression analysis
mkdir -p $OUTPUT_DIR/allelic_expression/

# Extract reads mapped to chromosome 6 and unmapped reads that contain valid cell barcode (CB) and UMI (UB) tags, retaining the SAM header
samtools view -h $OUTPUT_DIR/cellranger_count/outs/possorted_genome_bam.bam chr6 | awk '$0 ~ /^@/ || ($0 ~ /\tCB:Z:/ && $0 ~ /\tUB:Z:/)' > $OUTPUT_DIR/allelic_expression/chr6_mapped_reads.sam
samtools view -h -f 4 $OUTPUT_DIR/cellranger_count/outs/possorted_genome_bam.bam | awk '$0 ~ /^@/ || ($0 ~ /\tCB:Z:/ && $0 ~ /\tUB:Z:/)' > $OUTPUT_DIR/allelic_expression/unmapped_reads.sam
# Convert SAM files to BAM and merge
samtools view -b -o $OUTPUT_DIR/allelic_expression/chr6_mapped_reads.bam $OUTPUT_DIR/allelic_expression/chr6_mapped_reads.sam
samtools view -b -o $OUTPUT_DIR/allelic_expression/unmapped_reads.bam $OUTPUT_DIR/allelic_expression/unmapped_reads.sam
samtools merge -o $OUTPUT_DIR/allelic_expression/chr6_and_unmapped_reads.bam $OUTPUT_DIR/allelic_expression/chr6_mapped_reads.bam $OUTPUT_DIR/allelic_expression/unmapped_reads.bam
# Remove intermediate SAM and BAM files to save disk space
rm $OUTPUT_DIR/allelic_expression/chr6_mapped_reads.sam $OUTPUT_DIR/allelic_expression/unmapped_reads.sam $OUTPUT_DIR/allelic_expression/chr6_mapped_reads.bam $OUTPUT_DIR/allelic_expression/unmapped_reads.bam

# Convert merged BAM file to FASTQ for downstream allele-specific alignment
samtools fastq $OUTPUT_DIR/allelic_expression/chr6_and_unmapped_reads.bam > $OUTPUT_DIR/allelic_expression/chr6_and_unmapped_reads.fastq

# Create a TSV file listing read ID, cell barcode, UMI, chromosome, and genomic position for all reads with valid CB and UB tags
samtools view $OUTPUT_DIR/allelic_expression/chr6_and_unmapped_reads.bam | \
awk '{
  read_id=$1;
  chr=$3;
  pos=$4;
  cb="NA";
  ub="NA";
  for(i=12;i<=NF;i++){
    if($i ~ /^CB:Z:/) { cb=substr($i,6) }
    if($i ~ /^UB:Z:/) { ub=substr($i,6) }
  }
  if(cb != "NA" && ub != "NA") {
    print read_id"\t"cb"\t"ub"\t"chr"\t"pos
  }
}' > $OUTPUT_DIR/allelic_expression/chr6_and_unmapped_reads.tsv

# Align extracted reads against arcasHLA-derived HLA allele sequences to quantify allele-specific expression
vsearch --usearch_global $OUTPUT_DIR/allelic_expression/chr6_and_unmapped_reads.fastq --db $OUTPUT_DIR/arcashla_genotype/genotype.fasta \
  --id 0.96 \
  --query_cov 1.0 \
  --maxaccepts 0 \
  --maxrejects 0 \
  --userfields query+target+id+mism+gaps+tilo+tihi \
  --userout $OUTPUT_DIR/allelic_expression/chr6_and_unmapped_realigned.tsv


# -------------------------------
# 
# ------------------------------- 

# 
$SCRIPT_DIR/scripts/calculate_allele_count_matrix.R \
  --reads $OUTPUT_DIR/allelic_expression/chr6_and_unmapped_reads.tsv \
  --alignments $OUTPUT_DIR/allelic_expression/chr6_and_unmapped_realigned.tsv \
  --gtf $REF_TRANSCRIPTOME/genes/genes.gtf.gz \
  --output-dir $OUTPUT_DIR/allelic_expression/